run-name: ${{ github.actor }} triggered ${{ github.event_name }} on ${{ github.ref_name }}

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build distribution ðŸ“¦
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Check if tag is on main branch
      run: |
        COMMIT=$(git rev-list -n 1 ${{ github.ref }})
        echo "$COMMIT"
        BRANCH2=$(git branch -r --contains $COMMIT | grep -w 'origin/test2')
        echo "test1"
        echo "branch $BRANCH2"
        echo "test2"
        BRANCH=$(git branch -r --contains $COMMIT | grep -w 'origin/test' || true)
        echo "branch $BRANCH"
        if [[ -n "$BRANCH2" ]]; then
            echo "This tag is on the main branch"
        else
            echo "This tag is not on the main branch"
            exit 1
        fi